/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package begin;

import com.formdev.flatlaf.FlatLightLaf;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author hecto
 */
public class Shop extends javax.swing.JFrame {

    int goldPoints = 3975;
    int saphirePoints = 5000;
    Integer botaoClicado = null;
    List<Item> itens = new ArrayList<>();
    List<JButton> jButtonsItens = new ArrayList<>();
    List<JLabel> jLabelsItensValores = new ArrayList<>();
    List<JLabel> jLabelsItensNomes = new ArrayList<>();
    MouseAdapter adapterMouse;
    Clip clip = AudioSystem.getClip();
    AudioInputStream ais = AudioSystem.getAudioInputStream(getClass().getResource("/buy.wav"));

    /**
     * Creates new form Shop
     */
    public Shop() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        popularLoja();
        initComponents();
        clip.open(ais);
        popularListaBotoes();
        popularListaLabels();
        popularListaValores();
        nameLabels();
        setLabelsValues();
        iniciarListener();
        setStateButtons();
        setLabelsIcons();
        setButtonsIcons();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbGold = new javax.swing.JLabel();
        jLbSaphire = new javax.swing.JLabel();
        jBtnVoidSword = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBtnRunicSword = new javax.swing.JButton();
        jBtnNormalSword = new javax.swing.JButton();
        jBtnGoldenSword = new javax.swing.JButton();
        jLbValorItem1 = new javax.swing.JLabel();
        jLbValorItem2 = new javax.swing.JLabel();
        jLbValorItem3 = new javax.swing.JLabel();
        jLbValorItem4 = new javax.swing.JLabel();
        jLbItem2 = new javax.swing.JLabel();
        jLbItem1 = new javax.swing.JLabel();
        jLbItem4 = new javax.swing.JLabel();
        jLbItem3 = new javax.swing.JLabel();
        jBtnBroquel = new javax.swing.JButton();
        jLbItem5 = new javax.swing.JLabel();
        jLbValorItem5 = new javax.swing.JLabel();
        jBtnLivroPerdicao = new javax.swing.JButton();
        jLbItem6 = new javax.swing.JLabel();
        jLbValorItem6 = new javax.swing.JLabel();
        jBtnAnelDourado = new javax.swing.JButton();
        jLbItem7 = new javax.swing.JLabel();
        jLbValorItem7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbGold.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLbGold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold (1).png"))); // NOI18N
        jLbGold.setText(String.valueOf(goldPoints));

        jLbSaphire.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLbSaphire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saphire (1).png"))); // NOI18N
        jLbSaphire.setText(String.valueOf(saphirePoints));

        jBtnVoidSword.setName("3"); // NOI18N

        jBtnRunicSword.setName("4"); // NOI18N

        jBtnNormalSword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sword.png"))); // NOI18N
        jBtnNormalSword.setName("1"); // NOI18N
        jBtnNormalSword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNormalSwordMouseClicked(evt);
            }
        });

        jBtnGoldenSword.setName("2"); // NOI18N

        jLbValorItem1.setText(String.valueOf(itens.get(0).getValor()));

        jLbValorItem2.setText(String.valueOf(itens.get(1).getValor()));

        jLbValorItem3.setText(String.valueOf(itens.get(2).getValor()));

        jLbValorItem4.setText(String.valueOf(itens.get(3).getValor()));

        jLbItem2.setText(itens.get(1).getNome());

        jLbItem1.setText(itens.get(0).getNome());

        jLbItem4.setText(itens.get(3).getNome());

        jLbItem3.setText(itens.get(2).getNome());

        jBtnBroquel.setName("1"); // NOI18N
        jBtnBroquel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBroquelMouseClicked(evt);
            }
        });

        jLbItem5.setText(itens.get(3).getNome());

        jLbValorItem5.setText(String.valueOf(itens.get(3).getValor()));

        jBtnLivroPerdicao.setName("1"); // NOI18N
        jBtnLivroPerdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLivroPerdicaoMouseClicked(evt);
            }
        });

        jLbItem6.setText(itens.get(3).getNome());

        jLbValorItem6.setText(String.valueOf(itens.get(3).getValor()));

        jBtnAnelDourado.setName("1"); // NOI18N
        jBtnAnelDourado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnelDouradoMouseClicked(evt);
            }
        });

        jLbItem7.setText(itens.get(3).getNome());

        jLbValorItem7.setText(String.valueOf(itens.get(3).getValor()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbGold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbSaphire)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLbItem1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jBtnNormalSword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLbItem2)
                            .addComponent(jBtnGoldenSword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbValorItem2)
                            .addComponent(jLbItem6)
                            .addComponent(jBtnLivroPerdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbValorItem6))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jBtnVoidSword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbItem3)
                            .addComponent(jLbValorItem3)
                            .addComponent(jLbItem7)
                            .addComponent(jBtnAnelDourado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbValorItem7))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLbItem4)
                            .addComponent(jBtnRunicSword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbValorItem4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLbItem5)
                            .addComponent(jBtnBroquel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbValorItem5)
                            .addComponent(jLbValorItem1))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbGold)
                    .addComponent(jLbSaphire))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtnRunicSword, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNormalSword, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVoidSword, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGoldenSword, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbItem2)
                    .addComponent(jLbItem3)
                    .addComponent(jLbItem4)
                    .addComponent(jLbItem1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLbValorItem2)
                    .addComponent(jLbValorItem1)
                    .addComponent(jLbValorItem3)
                    .addComponent(jLbValorItem4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnBroquel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLbItem5)
                        .addGap(18, 18, 18)
                        .addComponent(jLbValorItem5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnLivroPerdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLbItem6)
                        .addGap(18, 18, 18)
                        .addComponent(jLbValorItem6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAnelDourado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLbItem7)
                        .addGap(18, 18, 18)
                        .addComponent(jLbValorItem7)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNormalSwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNormalSwordMouseClicked


    }//GEN-LAST:event_jBtnNormalSwordMouseClicked

    private void jBtnBroquelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBroquelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBroquelMouseClicked

    private void jBtnLivroPerdicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLivroPerdicaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLivroPerdicaoMouseClicked

    private void jBtnAnelDouradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnelDouradoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAnelDouradoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Shop().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    Logger.getLogger(Shop.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void popularLoja() {
        itens.add(new Item("Normal Sword", "Uma espada normal, mas afiada.", 975, "/sword (4).png"));
        itens.add(new ItemLendario("Golden Sword", "A espada de ouro que pode proporcionar rios de ouro.", 2750, "\nAtaque +15\nPoder +5", "/sword (1).png"));
        itens.add(new ItemLendario("Void Sword", "Uma espada forjada nos primórdios da criação do Universo. Como é bom ter parte do universo nas mãos...", 7000, "\nPoder +???", "/sword (2).png"));
        itens.add(new ItemLendario("Runic Sword", "A espada queridinha dos magos de batalha. Faz pensar em abandonar os livros de magia.", 5000, "\nAtaque +7\nPoder + 13", "/sword (3).png"));
        itens.add(new Item("Broquel de Madeira", "Um escudo básico que pode salvar tua pele durante as batalhas.", 550, "/shield (1).png"));
        itens.add(new ItemLendario("Livro da Perdição", "Um livro carregado de poder maligno. Os antigos deuses profanos depositavam sua escuridão neste livro", 4500, "\nPoder + 50", "/book.png"));
        itens.add(new Item("Anel Brilhante", "Um anel estiloso.", 250, "/diamond-ring.png"));
    }

    private void popularListaBotoes() {
        jButtonsItens.add(jBtnNormalSword);
        jButtonsItens.add(jBtnGoldenSword);
        jButtonsItens.add(jBtnVoidSword);
        jButtonsItens.add(jBtnRunicSword);
        jButtonsItens.add(jBtnBroquel);
        jButtonsItens.add(jBtnLivroPerdicao);
        jButtonsItens.add(jBtnAnelDourado);
    }

    private Item getItem(int id) {
        Item valor = itens.stream().filter(x -> x.getId() == id).collect(Collectors.toList()).get(0);
        return valor;
    }

    private int getValorBotao(MouseEvent e) {
        int valor = jButtonsItens.indexOf(e.getSource());
        return valor;
    }

    private void iniciarListener() {
        adapterMouse = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Item itemSelecionado = getItem(jButtonsItens.indexOf(e.getSource()) + 1);

                if (e.getButton() == MouseEvent.BUTTON1) {
                    JPanelDescricao.iniciarJPanelDescricao(itemSelecionado, Shop.this);
                }
                

                if (e.getButton() == MouseEvent.BUTTON3) {
                    switch (itemSelecionado.getMoeda().ordinal()) {
                        case 0:
                            comprar(itemSelecionado, goldPoints);
                            break;
                        case 1:
                            comprar(itemSelecionado, saphirePoints);
                            break;

                    }
                }
            }
        };

        for (var jBtnItem : jButtonsItens) {
            jBtnItem.addMouseListener(adapterMouse);
        }

    }

    public JLabel getjLbGold() {
        return jLbGold;
    }

    public void setjLbGold(JLabel jLbGold) {
        this.jLbGold = jLbGold;
    }

    public void setStateButtons() {
        for (var jButton : jButtonsItens) {
            if (goldPoints < getItem(jButtonsItens.indexOf(jButton) + 1).getValor() && getItem(jButtonsItens.indexOf(jButton) + 1).getMoeda() == Moeda.GOLD
                    || saphirePoints < getItem(jButtonsItens.indexOf(jButton) + 1).getValor() && getItem(jButtonsItens.indexOf(jButton) + 1).getMoeda() == Moeda.SAPHIRE) {
                jButton.setEnabled(false);
            } else {
                jButton.setEnabled(true);
            }
        }
    }

    public void comprar(Item item, int moeda) {
        if (moeda >= item.getValor()) {
            moeda -= item.getValor();
            System.out.println(item.getValor());
            System.out.println("Item comprado!");

            if (item.getMoeda() == Moeda.GOLD) {
                goldPoints = moeda;
                jLbGold.setText(String.valueOf(moeda));
            } else {
                saphirePoints = moeda;
                jLbSaphire.setText(String.valueOf(moeda));
            }
            
            clip.loop(1);
            setStateButtons();
            if (!clip.isActive()){
                clip.close();
            }

        }
    }

    private void nameLabels() {
        for (int i = 0; i < jLabelsItensNomes.size(); i++) {
            jLabelsItensNomes.get(i).setText(getItem(jLabelsItensNomes.indexOf(jLabelsItensNomes.get(i)) + 1).getNome());
        }
    }

    private void setLabelsValues() {
        for (int i = 0; i < jLabelsItensValores.size(); i++) {
            jLabelsItensValores.get(i).setText(String.valueOf(getItem(jLabelsItensValores.indexOf(jLabelsItensValores.get(i)) + 1).getValor()));
        }
    }

    private void setLabelsIcons() {
        for (int i = 0; i < jLabelsItensValores.size(); i++) {
            jLabelsItensValores.get(i).setIcon(new ImageIcon(getClass().getResource(Moeda.getUrlImage(getItem(jLabelsItensValores.indexOf(jLabelsItensValores.get(i)) + 1).getMoeda()))));
        }

    }

    private void setButtonsIcons() {
        for (int i = 0; i < jButtonsItens.size(); i++) {
            jButtonsItens.get(i).setIcon(new ImageIcon(getClass().getResource(getItem(jButtonsItens.indexOf(jButtonsItens.get(i)) + 1).getUrlImage())));
        }
    }

    private void popularListaLabels() {
        jLabelsItensNomes.add(jLbItem1);
        jLabelsItensNomes.add(jLbItem2);
        jLabelsItensNomes.add(jLbItem3);
        jLabelsItensNomes.add(jLbItem4);
        jLabelsItensNomes.add(jLbItem5);
        jLabelsItensNomes.add(jLbItem6);
        jLabelsItensNomes.add(jLbItem7);
    }

    private void popularListaValores() {
        jLabelsItensValores.add(jLbValorItem1);
        jLabelsItensValores.add(jLbValorItem2);
        jLabelsItensValores.add(jLbValorItem3);
        jLabelsItensValores.add(jLbValorItem4);
        jLabelsItensValores.add(jLbValorItem5);
        jLabelsItensValores.add(jLbValorItem6);
        jLabelsItensValores.add(jLbValorItem7);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnelDourado;
    private javax.swing.JButton jBtnBroquel;
    private javax.swing.JButton jBtnGoldenSword;
    private javax.swing.JButton jBtnLivroPerdicao;
    private javax.swing.JButton jBtnNormalSword;
    private javax.swing.JButton jBtnRunicSword;
    private javax.swing.JButton jBtnVoidSword;
    private javax.swing.JLabel jLbGold;
    private javax.swing.JLabel jLbItem1;
    private javax.swing.JLabel jLbItem2;
    private javax.swing.JLabel jLbItem3;
    private javax.swing.JLabel jLbItem4;
    private javax.swing.JLabel jLbItem5;
    private javax.swing.JLabel jLbItem6;
    private javax.swing.JLabel jLbItem7;
    private javax.swing.JLabel jLbSaphire;
    private javax.swing.JLabel jLbValorItem1;
    private javax.swing.JLabel jLbValorItem2;
    private javax.swing.JLabel jLbValorItem3;
    private javax.swing.JLabel jLbValorItem4;
    private javax.swing.JLabel jLbValorItem5;
    private javax.swing.JLabel jLbValorItem6;
    private javax.swing.JLabel jLbValorItem7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
